### ISSUE TITLE
Reporting p-values in tidy_summary.summary.rms

### ISSUE THREAD

**Issue by ferenci-tamas** [CorradoLanera/depigner#36]
I think it'd be nice if `tidy_summary` would - or there would be an option to do so - report p-values. (Of course that would require taking the fitted model itself as an argument not its `summary`.)

**Comment by CorradoLanera** [comment]
Just pass `test = TRUE` to the previous `summary()` call (using the `summary()` function from `{Hmisc}`, in particular for `method = "reverse"`). 

You can further personalize the output using, e.g., the `prtest = c('P','stat','df','name')` option in `tidy_summary()`. Use that as you would be the `print()` method for the `summary()`. You can see all the available options at `?Hmisc::summary.formula`. All the options you will pass to `tidy_summary()` will be passed to the `print()` methods listed there (so, you can use all the option listed there).

Please let me know if this solves your issue.

**Comment by ferenci-tamas** [comment]
Thanks for the answer @CorradoLanera ! Sorry, I wasn't specific enough: I was talking about applying `tidy_summary` to a summary of a fitted model from `rms` not an Hmisc `summary`.

**Comment by CorradoLanera** [comment]
I am thinking to implement a solution with API similar to `summary_interact()`. Powered by `ci2p()` it won't require to passing the model directly to the function.

So, add an optional argoument `p = FALSE` at the end of the call (after the dots, i. e. you will be required to write it explicitly without possibility to use positional argument matching).

@danielebottigliengo what do you think?

**Comment by danielebottigliengo** [comment]
Yeah, it sounds good!

**Comment by CorradoLanera** [comment]
@danielebottigliengo I think that `{rms}` object can be too many different objects to handle all of them correctly (`cph`, `ols`, `lrm`, `Glm`, ...). 
I think it is better to provide a `tidy_summary.anova.rms()` method for the output of `rms:::anova.rms()` and tidy convert the model's ANOVA output as computed directly by `{rms}` to retrieve the p-values.

```
mod <- rms::<whathever_rms_model>(...)
anova_mod <- anova(mod) # managed by {rms} directly with all its power
tidy_summary(anova_mod)
```
Or we can provide a new function like `tidy_anova()` as a wrapper to `{rms}`'s ANOVA so you can directly call:

```
tidy_anova(mod)
```

What do you think? @tamas-ferenci, you would you prefer or consider more robust/convenient/useful?

Another final option is to provide a `tidy_anova()` to be use alone, and an option `p = FALSE` to `tidy_summary()` which uses `tidy_anova()` internally to compute and bind the p-values to the results.
```
tidy_anova(mod) # return a tidy tibble for the ANOVA
tidy_summary(mod, p = TRUE) # return the usual summary with P-values too
```

Anyway, we have to correctly manage and consider borderline cases, like usage of splines, interactions, ... I think we can start providing `tidy_anova()` and start to study how to include its results in the `tidy_summary()` too.

What's your opinion?

**Comment by ferenci-tamas** [comment]
I agree that `ci2p` should not be used, as many p-values and CIs are far from normal approximation in `rms`.

However, I don't see any major problem with passing the model to the function, you could even have something like `summod <- summary(mod)` as the first line, and then you'll have everything as in the current version. (OK, I understand that it'd be a non-backward compatible change in syntax.)

There is one problem that I see with using `anova`, namely, categorical variables (and spline expansions as well). There you'll have only one p-value with `anova` for the variable, but as many p-values in the fitted model as the number of levels (minus 1). So - theoretically! - the most robust and comprehensive solution would be perhaps to provide *two* sets of p-values, a global one from the `anova` and the individual ones. (Of course I understand that this might be a lot of work.)

**Comment by CorradoLanera** [comment]
I am not sure about that; the main aim of those functions in the `{depigner}` is to convert to nice and usable `tibble`s the `{rms}` and `{Hmisc}` summaries, not to expand them.

I am  more incline to provide a `tidy_anova.rms()` and a `tidy_print.rms()` methods (you will run simply as `tidy_anova(mod)` and `tidy_print(mod)`).

**Comment by CorradoLanera** [comment]
Depending on the distribution of data and hypotheses one would like to test, there are too many different possible p-values options. The aim of `{depigner}` is not to provide a statistical tool but to manage standard and repeat annoying stuff (with methods well designed from other packages). So, I prefer not to fix this issue. Sorry.

**Comment by ferenci-tamas** [comment]
OK, thanks for considering it!
