### ISSUE TITLE
Add packages to install_pkg_set

### ISSUE THREAD

**Issue by Eligallo** [CorradoLanera/depigner#47]
Could you please add "dlnm", "writexl", "ggeffects" and "ggpubr" to install_pkg_set()?

**Comment by CorradoLanera** [comment]
Can you specify in which set you would like to include each of them? (see the [pkg_sets.R](https://github.com/CorradoLanera/depigner/blob/master/R/pkg_sets.R))

If a package "a" imports a package "b," you do not need to list "b" too: "b" will be automatically installed anyway when "a" will be installed. Please, with `depigner::imported_from("<package_name>")` check if you must add all of them and if you can remove some of the currently listed into the sets you will have identified. 

Thank you.

**Comment by Eligallo** [comment]
You can include "writexl", "ggpubr"  and "ggeffects" in pkg_utils , "dlnm" in pkg_stat.
There are no packages to remove.

**Comment by CorradoLanera** [comment]
add also: `{renv}`, `{targets}`, `{tarchetypes}`, and `{checkmate}`
