### ISSUE TITLE
Problem with ci2p function

### ISSUE THREAD

**Issue by danielebottigliengo** [CorradoLanera/depigner#6]
Hi,

when I use the function _ci2p_ I get the following error

```r
library(depigner)

est <- 5.10
lower <- 1.25
upper <- 9.25

ci2p(est, lower, upper)
```

However if I call the function as follows everything seems to work properly

```r
library(depigner)

est <- 5.10
lower <- 1.25
upper <- 9.25

depigner:::ci2p(est, lower, upper)
```

I think there may be an exportation issue related to the function.

Thanks for this wonderful package!

Daniele

**Comment by CorradoLanera** [comment]
Yes, it was not exported by choice (I did not think it would be useful alone). Fixed (by the next release). Thanks.
